Repository TeamMemeSphere/Backend-MemeSphere, pull requests merged in 2025-01, with the labels that each got.

#9 #4,#5 Feat: 대시보드 상단 관련 controller 구현
  src/main/java/com/memesphere/controller/DashboardController.java
  src/main/java/com/memesphere/dto/DashboardDTO.java
  src/main/java/com/memesphere/service/dashboard/DashboardService.java
  src/main/java/com/memesphere/service/dashboard/DashboardServiceImpl.java
Labels: ✨ Feature

#12 #6 Feat: 스프링 시큐리티 설정
  build.gradle
  src/main/java/com/memesphere/config/SecurityConfig.java
Labels: ✨ Feature

#13 #11 Feat: 알림 관련 controller 구현
  src/main/java/com/memesphere/controller/CoinNotificationController.java
  src/main/java/com/memesphere/controller/PushNotificationController.java
  src/main/java/com/memesphere/dto/NotificationDTO.java
  src/main/java/com/memesphere/service/coinNotification/CoinNotificationService.java
  src/main/java/com/memesphere/service/coinNotification/CoinNotificationServiceImpl.java
Labels: ✨ Feature

#14 #10 Feat: 컬렉션/검색 기능 관련 controller 구현
  src/main/java/com/memesphere/controller/CollectionRestController.java
  src/main/java/com/memesphere/controller/SearchRestController.java
  src/main/java/com/memesphere/converter/CollectionConverter.java
  src/main/java/com/memesphere/converter/SearchConverter.java
  src/main/java/com/memesphere/dto/CollectionResponseDTO.java
  src/main/java/com/memesphere/dto/SearchResponseDTO.java
  src/main/java/com/memesphere/repository/CollectionRepository.java
  src/main/java/com/memesphere/repository/UserRepository.java
  src/main/java/com/memesphere/service/collectionService/CollectionQueryService.java
  src/main/java/com/memesphere/service/collectionService/CollectionQueryServiceImpl.java
  src/main/java/com/memesphere/service/searchService/SearchQueryService.java
  src/main/java/com/memesphere/service/searchService/SearchQueryServiceImpl.java
  src/main/java/com/memesphere/validation/annotation/CheckPage.java
  src/main/java/com/memesphere/validation/validator/PageCheckValidator.java
Labels: ✨ Feature

#18 #17 Feat: 실시간 채팅 사용자 접속 기능 구현
  build.gradle
  src/main/java/com/memesphere/MemesphereApplication.java
  src/main/java/com/memesphere/apipayload/code/status/ErrorStatus.java
  src/main/java/com/memesphere/config/StompWebSocketConfig.java
  src/main/java/com/memesphere/controller/ChatController.java
  src/main/java/com/memesphere/controller/TestController.java
  src/main/java/com/memesphere/converter/ChatConverter.java
  src/main/java/com/memesphere/converter/TempConverter.java
  src/main/java/com/memesphere/domain/Chat.java
  src/main/java/com/memesphere/domain/common/BaseEntity.java
  src/main/java/com/memesphere/dto/request/ChatRequest.java
  src/main/java/com/memesphere/dto/response/ChatResponse.java
  src/main/java/com/memesphere/dto/response/TempResponse.java
  src/main/java/com/memesphere/repository/MemeRepository.java
  src/main/java/com/memesphere/repository/chat/ChatCustomRepository.java
  src/main/java/com/memesphere/repository/chat/ChatCustomRepositoryImpl.java
  src/main/java/com/memesphere/repository/chat/ChatRepository.java
  src/main/java/com/memesphere/service/ChatService.java
Labels: ✨ Feature

#23 #22 Feat: 컬렉션/검색 기능 구현
  src/main/java/com/memesphere/apipayload/code/status/ErrorStatus.java
  src/main/java/com/memesphere/controller/CollectionRestController.java
  src/main/java/com/memesphere/controller/SearchRestController.java
  src/main/java/com/memesphere/converter/CollectionConverter.java
  src/main/java/com/memesphere/converter/SearchConverter.java
  src/main/java/com/memesphere/domain/ChartData.java
  src/main/java/com/memesphere/domain/Collection.java
  src/main/java/com/memesphere/domain/MemeCoin.java
  src/main/java/com/memesphere/domain/enums/SortType.java
  src/main/java/com/memesphere/domain/enums/ViewType.java
  src/main/java/com/memesphere/dto/CollectionResponseDTO.java
  src/main/java/com/memesphere/dto/SearchResponseDTO.java
  src/main/java/com/memesphere/dto/response/CollectionPageResponse.java
  src/main/java/com/memesphere/dto/response/CollectionPreviewResponse.java
  src/main/java/com/memesphere/dto/response/SearchGridPreviewResponse.java
  src/main/java/com/memesphere/dto/response/SearchListPreviewResponse.java
  src/main/java/com/memesphere/dto/response/SearchPageResponse.java
  src/main/java/com/memesphere/repository/CollectionRepository.java
  src/main/java/com/memesphere/repository/MemeRepository.java
  src/main/java/com/memesphere/service/collectionService/CollectionQueryService.java
  src/main/java/com/memesphere/service/collectionService/CollectionQueryServiceImpl.java
  src/main/java/com/memesphere/service/searchService/SearchQueryService.java
  src/main/java/com/memesphere/service/searchService/SearchQueryServiceImpl.java
Labels: ✨ Feature

#20 #19 Feat: 밈코인 상세 정보 조회 기능 구현
  src/main/java/com/memesphere/apipayload/code/status/ErrorStatus.java
  src/main/java/com/memesphere/controller/DetailController.java
  src/main/java/com/memesphere/converter/DetailConverter.java
  src/main/java/com/memesphere/domain/MemeCoin.java
  src/main/java/com/memesphere/dto/response/DetailGetResponse.java
  src/main/java/com/memesphere/service/DetailService.java
Labels: ✨ Feature

#24 #4 Feat: 대시보드 상단 조회 기능 구현
  src/main/java/com/memesphere/controller/DashboardController.java
  src/main/java/com/memesphere/converter/DashboardConverter.java
  src/main/java/com/memesphere/domain/MemeCoin.java
  src/main/java/com/memesphere/dto/DashboardDTO.java
  src/main/java/com/memesphere/dto/response/DashboardOverviewResponse.java
  src/main/java/com/memesphere/dto/response/DashboardTrendListResponse.java
  src/main/java/com/memesphere/dto/response/DashboardTrendResponse.java
  src/main/java/com/memesphere/repository/ChartDataRepository.java
  src/main/java/com/memesphere/repository/MemeCoinRepository.java
  src/main/java/com/memesphere/service/dashboard/DashboardService.java
  src/main/java/com/memesphere/service/dashboard/DashboardServiceImpl.java
  src/main/java/com/memesphere/service/dashboardService/DashboardQueryService.java
  src/main/java/com/memesphere/service/dashboardService/DashboardQueryServiceImpl.java
Labels: ✨ Feature

#25 #7, #8 Feat: 카카오 로그인 구현
  build.gradle
  src/main/java/com/memesphere/apipayload/code/status/ErrorStatus.java
  src/main/java/com/memesphere/config/SecurityConfig.java
  src/main/java/com/memesphere/controller/TestLoginController.java
  src/main/java/com/memesphere/controller/UserController.java
  src/main/java/com/memesphere/converter/UserConverter.java
  src/main/java/com/memesphere/domain/User.java
  src/main/java/com/memesphere/dto/response/KakaoTokenResponse.java
  src/main/java/com/memesphere/dto/response/KakaoUserInfoResponse.java
  src/main/java/com/memesphere/dto/response/LoginResponse.java
  src/main/java/com/memesphere/dto/response/UserInfoResponse.java
  src/main/java/com/memesphere/jwt/JwtAuthenticationFilter.java
  src/main/java/com/memesphere/jwt/TokenProvider.java
  src/main/java/com/memesphere/repository/UserRepository.java
  src/main/java/com/memesphere/service/user/KakaoService.java
  src/main/java/com/memesphere/service/user/KakaoServiceImpl.java
  src/main/java/com/memesphere/service/user/UserService.java
  src/main/java/com/memesphere/service/user/UserServiceImpl.java
  src/main/resources/templates/login.html
Labels: ✨ Feature

#32 #30 Fix: market cap 대체 반영
  src/main/java/com/memesphere/controller/SearchRestController.java
  src/main/java/com/memesphere/converter/CollectionConverter.java
  src/main/java/com/memesphere/converter/DashboardConverter.java
  src/main/java/com/memesphere/converter/SearchConverter.java
  src/main/java/com/memesphere/domain/ChartData.java
  src/main/java/com/memesphere/domain/enums/SortType.java
  src/main/java/com/memesphere/dto/response/CollectionPreviewResponse.java
  src/main/java/com/memesphere/dto/response/SearchGridPreviewResponse.java
  src/main/java/com/memesphere/dto/response/SearchListPreviewResponse.java
  src/main/java/com/memesphere/service/searchService/SearchQueryServiceImpl.java
Labels: 🎀 Fix

#36 #35 Feat: 코인 별 최신 채팅 기능 구현
  src/main/java/com/memesphere/MemesphereApplication.java
  src/main/java/com/memesphere/chat/controller/ChatController.java
  src/main/java/com/memesphere/chat/converter/ChatConverter.java
  src/main/java/com/memesphere/chat/domain/Chat.java
  src/main/java/com/memesphere/chat/dto/response/ChatResponse.java
  src/main/java/com/memesphere/chat/repository/ChatCustomRepository.java
  src/main/java/com/memesphere/chat/repository/ChatCustomRepositoryImpl.java
  src/main/java/com/memesphere/chat/repository/ChatRepository.java
  src/main/java/com/memesphere/chat/service/ChatService.java
Labels: ✨ Feature

#37 #26 Feat: 일반 로그인 구현
  src/main/java/com/memesphere/domain/user/controller/UserController.java
  src/main/java/com/memesphere/domain/user/converter/UserConverter.java
  src/main/java/com/memesphere/domain/user/dto/request/SignInRequest.java
  src/main/java/com/memesphere/domain/user/dto/request/SignUpRequest.java
  src/main/java/com/memesphere/domain/user/dto/response/TokenResponse.java
  src/main/java/com/memesphere/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/memesphere/domain/user/entity/User.java
  src/main/java/com/memesphere/domain/user/entity/UserRole.java
  src/main/java/com/memesphere/domain/user/repository/UserRepository.java
  src/main/java/com/memesphere/domain/user/service/AuthService.java
  src/main/java/com/memesphere/domain/user/service/AuthServiceImpl.java
  src/main/java/com/memesphere/domain/user/service/KakaoService.java
  src/main/java/com/memesphere/domain/user/service/KakaoServiceImpl.java
  src/main/java/com/memesphere/domain/user/service/UserService.java
  src/main/java/com/memesphere/domain/user/service/UserServiceImpl.java
  src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/memesphere/global/config/SecurityConfig.java
  src/main/java/com/memesphere/global/jwt/CustomUserDetails.java
  src/main/java/com/memesphere/global/jwt/CustomUserDetailsServiceImpl.java
  src/main/java/com/memesphere/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/memesphere/global/jwt/TokenProvider.java
Labels: ✨ Feature

#41 #27 밈코인 정보 DB 저장 (Binance API 연결)
  src/main/java/com/memesphere/MemesphereApplication.java
  src/main/java/com/memesphere/binance/dto/response/BinanceTickerResponse.java
  src/main/java/com/memesphere/binance/service/BinanceQueryService.java
  src/main/java/com/memesphere/binance/service/BinanceQueryServiceImpl.java
  src/main/java/com/memesphere/domain/chartdata/converter/ChartDataConverter.java
  src/main/java/com/memesphere/domain/chartdata/entity/ChartData.java
  src/main/java/com/memesphere/domain/chartdata/repository/ChartDataRepository.java
  src/main/java/com/memesphere/domain/chartdata/scheduler/ChartDataScheduler.java
  src/main/java/com/memesphere/domain/chartdata/service/ChartDataQueryService.java
  src/main/java/com/memesphere/domain/chartdata/service/ChartDataQueryServiceImpl.java
  src/main/java/com/memesphere/domain/chat/service/ChatService.java
  src/main/java/com/memesphere/domain/collection/controller/CollectionRestController.java
  src/main/java/com/memesphere/domain/collection/converter/CollectionConverter.java
  src/main/java/com/memesphere/domain/dashboard/controller/DashboardController.java
  src/main/java/com/memesphere/domain/memecoin/MemeCoinInitializer.java
  src/main/java/com/memesphere/domain/memecoin/entity/MemeCoin.java
  src/main/java/com/memesphere/domain/memecoin/repository/MemeCoinRepository.java
  src/main/java/com/memesphere/domain/memecoin/service/MemeCoinQueryService.java
  src/main/java/com/memesphere/domain/memecoin/service/MemeCoinQueryServiceImpl.java
  src/main/java/com/memesphere/domain/search/controller/SearchRestController.java
  src/main/java/com/memesphere/domain/search/converter/SearchConverter.java
  src/main/java/com/memesphere/domain/search/dto/response/SearchGridPreviewResponse.java
  src/main/java/com/memesphere/domain/search/dto/response/SearchListPreviewResponse.java
  src/main/java/com/memesphere/domain/search/service/SearchQueryServiceImpl.java
  src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/memesphere/global/config/RestTemplateConfig.java
  src/main/resources/memecoin-storage/memecoin.json
Labels: ✨ Feature, 📬 API
