Repository TeamMemeSphere/Backend-MemeSphere, pull requests merged in 2025-02, with the labels that each got.

#42 #11 Feat: 알림 등록 API
  src/main/java/com/memesphere/domain/memecoin/repository/MemeCoinRepository.java
  src/main/java/com/memesphere/domain/notification/controller/CoinNotificationController.java
  src/main/java/com/memesphere/domain/notification/controller/PushNotificationController.java
  src/main/java/com/memesphere/domain/notification/converter/NotificationConverter.java
  src/main/java/com/memesphere/domain/notification/dto/NotificationDTO.java
  src/main/java/com/memesphere/domain/notification/dto/request/NotificationRequest.java
  src/main/java/com/memesphere/domain/notification/dto/response/NotificationListResponse.java
  src/main/java/com/memesphere/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/memesphere/domain/notification/entity/Notification.java
  src/main/java/com/memesphere/domain/notification/repository/NotificationRepository.java
  src/main/java/com/memesphere/domain/notification/service/CoinNotificationService.java
  src/main/java/com/memesphere/domain/notification/service/CoinNotificationServiceImpl.java
Labels: ✨ Feature

#46 #11 Feat: 알림 등록, 등록한 알림 조회 API
  src/main/java/com/memesphere/domain/memecoin/repository/MemeCoinRepository.java
  src/main/java/com/memesphere/domain/notification/controller/CoinNotificationController.java
  src/main/java/com/memesphere/domain/notification/controller/PushNotificationController.java
  src/main/java/com/memesphere/domain/notification/converter/NotificationConverter.java
  src/main/java/com/memesphere/domain/notification/dto/NotificationDTO.java
  src/main/java/com/memesphere/domain/notification/dto/request/NotificationRequest.java
  src/main/java/com/memesphere/domain/notification/dto/response/NotificationListResponse.java
  src/main/java/com/memesphere/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/memesphere/domain/notification/entity/Notification.java
  src/main/java/com/memesphere/domain/notification/repository/NotificationRepository.java
  src/main/java/com/memesphere/domain/notification/service/CoinNotificationService.java
  src/main/java/com/memesphere/domain/notification/service/CoinNotificationServiceImpl.java
Labels: ✨ Feature

#55 #45 Feat: Presigned URL 기능 구현
  build.gradle
  src/main/java/com/memesphere/domain/image/controller/ImageController.java
  src/main/java/com/memesphere/domain/image/service/ImageService.java
  src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/memesphere/global/config/AmazonConfig.java
Labels: ✨ Feature

#57 #56 Feat: 로그인 응답 형식에 닉네임 추가
  src/main/java/com/memesphere/domain/user/dto/response/LoginResponse.java
  src/main/java/com/memesphere/domain/user/service/AuthServiceImpl.java
  src/main/java/com/memesphere/domain/user/service/GoogleServiceImpl.java
  src/main/java/com/memesphere/domain/user/service/KakaoServiceImpl.java
Labels: ✨ Feature

#52 #51 Feat: 콜렉션 등록/삭제 기능
  src/main/java/com/memesphere/domain/chartdata/repository/ChartDataRepository.java
  src/main/java/com/memesphere/domain/collection/controller/CollectionRestController.java
  src/main/java/com/memesphere/domain/collection/converter/CollectionConverter.java
  src/main/java/com/memesphere/domain/collection/entity/Collection.java
  src/main/java/com/memesphere/domain/collection/repository/CollectionRepository.java
  src/main/java/com/memesphere/domain/collection/service/CollectionCommandService.java
  src/main/java/com/memesphere/domain/collection/service/CollectionCommandServiceImpl.java
  src/main/java/com/memesphere/domain/dashboard/controller/DashboardController.java
  src/main/java/com/memesphere/domain/dashboard/converter/DashboardConverter.java
  src/main/java/com/memesphere/domain/dashboard/dto/response/DashboardOverviewResponse.java
  src/main/java/com/memesphere/domain/dashboard/dto/response/DashboardTrendListResponse.java
  src/main/java/com/memesphere/domain/dashboard/dto/response/DashboardTrendResponse.java
  src/main/java/com/memesphere/domain/dashboard/service/DashboardQueryServiceImpl.java
  src/main/java/com/memesphere/domain/memecoin/entity/MemeCoinInitializer.java
  src/main/java/com/memesphere/domain/memecoin/repository/MemeCoinRepository.java
  src/main/java/com/memesphere/domain/notification/service/CoinNotificationServiceImpl.java
  src/main/java/com/memesphere/domain/user/repository/UserRepository.java
  src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#60 #51 Fix: 대시보드 차트 조회 api 로그인 여부 처리
  src/main/java/com/memesphere/domain/dashboard/controller/DashboardController.java
  src/main/java/com/memesphere/domain/dashboard/service/DashboardQueryService.java
  src/main/java/com/memesphere/domain/dashboard/service/DashboardQueryServiceImpl.java
Labels: 🎀 Fix

#61 #58 BugFix: s3 이미지 업로드 방식 수정 (Presigned Url)
  src/main/java/com/memesphere/domain/image/controller/ImageController.java
  src/main/java/com/memesphere/domain/image/converter/ImageConverter.java
  src/main/java/com/memesphere/domain/image/dto/request/ImageExtensionRequest.java
  src/main/java/com/memesphere/domain/image/dto/response/PresignedUrlResponse.java
  src/main/java/com/memesphere/domain/image/service/ImageService.java
  src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
Labels: 🐞 BugFix

#63 #59 Feat: 등록한 알림 삭제 API
  src/main/java/com/memesphere/domain/notification/controller/CoinNotificationController.java
  src/main/java/com/memesphere/domain/notification/dto/request/NotificationRequest.java
  src/main/java/com/memesphere/domain/notification/service/CoinNotificationServiceImpl.java
Labels: ✨ Feature

#50 #49 Setting: add cors configuration
  src/main/java/com/memesphere/global/config/CorsMvcConfig.java
Labels: ⚙ Setting

#70 #67 Feature: 검색, 컬렉션 기능에서 로그인 안 된 유저 처리 로직 추가
  src/main/java/com/memesphere/domain/collection/controller/CollectionRestController.java
  src/main/java/com/memesphere/domain/collection/service/CollectionQueryServiceImpl.java
  src/main/java/com/memesphere/domain/search/controller/SearchRestController.java
Labels: ✨ Feature

#72 #71 Fix: API 호출로 차트 데이터 DB 저장 (cron 방식)
  src/main/java/com/memesphere/domain/chartdata/scheduler/ChartDataScheduler.java
Labels: 📬 API

#54 #48 Feat: SSE를 이용한 실시간 알림 구현
  src/main/java/com/memesphere/domain/chartdata/repository/ChartDataRepository.java
  src/main/java/com/memesphere/domain/chat/controller/ChatController.java
  src/main/java/com/memesphere/domain/notification/controller/PushNotificationController.java
  src/main/java/com/memesphere/domain/notification/dto/request/SseSendRequest.java
  src/main/java/com/memesphere/domain/notification/repository/EmitterRepository.java
  src/main/java/com/memesphere/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/memesphere/domain/notification/repository/NotificationRepository.java
  src/main/java/com/memesphere/domain/notification/service/PushNotificationService.java
  src/main/java/com/memesphere/domain/notification/service/PushNotificationServiceImpl.java
  src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#69 #24 Fix: 대시보드 트렌드 api - 순위 방향(rankChangeDirection) 필드 반영
  src/main/java/com/memesphere/domain/dashboard/controller/DashboardController.java
  src/main/java/com/memesphere/domain/dashboard/converter/DashboardConverter.java
  src/main/java/com/memesphere/domain/dashboard/dto/response/DashboardTrendResponse.java
  src/main/java/com/memesphere/domain/dashboard/service/DashboardQueryServiceImpl.java
  src/main/java/com/memesphere/domain/memecoin/entity/MemeCoin.java
  src/main/java/com/memesphere/domain/memecoin/repository/MemeCoinRepository.java
  src/main/java/com/memesphere/global/config/SwaggerConfig.java
Labels: 🎀 Fix

#68 #66 카카오 계정 프로필 이미지 추가
  src/main/java/com/memesphere/domain/user/controller/UserController.java
  src/main/java/com/memesphere/domain/user/converter/UserConverter.java
  src/main/java/com/memesphere/domain/user/dto/response/KakaoUserInfoResponse.java
  src/main/java/com/memesphere/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/memesphere/domain/user/service/GoogleService.java
  src/main/java/com/memesphere/domain/user/service/GoogleServiceImpl.java
  src/main/java/com/memesphere/domain/user/service/KakaoService.java
  src/main/java/com/memesphere/domain/user/service/KakaoServiceImpl.java
  src/main/java/com/memesphere/global/config/SwaggerConfig.java
Labels: ✨ Feature

#74 #17 Feat: 실시간 채팅 전송, 조회 기능 추가
  src/main/java/com/memesphere/domain/chat/controller/ChatController.java
  src/main/java/com/memesphere/domain/chat/converter/ChatConverter.java
  src/main/java/com/memesphere/domain/chat/dto/request/ChatRequest.java
  src/main/java/com/memesphere/domain/chat/dto/response/ChatListResponse.java
  src/main/java/com/memesphere/domain/chat/entity/Chat.java
  src/main/java/com/memesphere/domain/chat/repository/ChatLikeRepository.java
  src/main/java/com/memesphere/domain/chat/repository/ChatRepository.java
  src/main/java/com/memesphere/domain/chat/service/ChatService.java
  src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/memesphere/global/config/StompWebSocketConfig.java
Labels: ✨ Feature

#77 #73 Chore: 밈코인 이미지 s3 업로드 및 db에 image url 저장
  src/main/resources/memecoin-storage/memecoin.json
Labels: 🛠️ Chore

#83 #82 Feat: 채팅 페이지네이션 기능 추가
  src/main/java/com/memesphere/domain/chat/controller/ChatController.java
  src/main/java/com/memesphere/domain/chat/converter/ChatConverter.java
  src/main/java/com/memesphere/domain/chat/dto/response/ChatListResponse.java
  src/main/java/com/memesphere/domain/chat/repository/ChatCustomRepository.java
  src/main/java/com/memesphere/domain/chat/repository/ChatCustomRepositoryImpl.java
  src/main/java/com/memesphere/domain/chat/repository/ChatRepository.java
  src/main/java/com/memesphere/domain/chat/service/ChatService.java
Labels: ✨ Feature

#81 #80 Feat: 실시간 알림 isOn 기능 추가
  src/main/java/com/memesphere/domain/chartdata/repository/ChartDataRepository.java
  src/main/java/com/memesphere/domain/chat/service/ChatService.java
  src/main/java/com/memesphere/domain/notification/controller/CoinNotificationController.java
  src/main/java/com/memesphere/domain/notification/converter/NotificationConverter.java
  src/main/java/com/memesphere/domain/notification/dto/request/NotificationRequest.java
  src/main/java/com/memesphere/domain/notification/entity/Notification.java
  src/main/java/com/memesphere/domain/notification/repository/EmitterRepository.java
  src/main/java/com/memesphere/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/memesphere/domain/notification/service/CoinNotificationService.java
  src/main/java/com/memesphere/domain/notification/service/CoinNotificationServiceImpl.java
  src/main/java/com/memesphere/domain/notification/service/PushNotificationService.java
  src/main/java/com/memesphere/domain/notification/service/PushNotificationServiceImpl.java
  src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#89 #88 Fix: 구글 로그인 redirect uri 설정
  src/main/java/com/memesphere/domain/user/controller/UserController.java
  src/main/java/com/memesphere/domain/user/service/GoogleService.java
  src/main/java/com/memesphere/domain/user/service/GoogleServiceImpl.java
Labels: 🎀 Fix

#91 #90 Fix: 실시간 채팅 withSockJS 적용
  src/main/java/com/memesphere/global/config/StompWebSocketConfig.java
Labels: 🎀 Fix

#79 #78 Fix: 서버 타임존 KST로 설정
  src/main/java/com/memesphere/MemesphereApplication.java
  src/main/java/com/memesphere/domain/chartdata/repository/ChartDataRepository.java
Labels: 🎀 Fix, 🌏 Deploy

#93 #92 Fix: 프로필 이미지 가져오는 방식 수정
  src/main/java/com/memesphere/domain/image/controller/ImageController.java
  src/main/java/com/memesphere/domain/image/service/ProfileService.java
Labels: 🎀 Fix

#95 #94 Fix: 웹소켓 CORS 설정 변경
  src/main/java/com/memesphere/global/config/StompWebSocketConfig.java
Labels: 🎀 Fix

#96 #1 Fix: docker-compose 파일 수정
  docker-compose.yml
Labels: ⚙ Setting

#97 #94 Fix: withSockJS 삭제
  src/main/java/com/memesphere/global/config/StompWebSocketConfig.java
Labels: 🎀 Fix

#98 #39 Chore: ErrorStatus 추가
  src/main/java/com/memesphere/domain/user/service/AuthServiceImpl.java
  src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/memesphere/global/jwt/TokenProvider.java
Labels: 🛠️ Chore

#100 #99 Fix: 알림 응답 isOn true로 나오도록 수정
  src/main/java/com/memesphere/domain/notification/converter/NotificationConverter.java
Labels: 🎀 Fix

#103 #99 Fix: fix notification converter
  src/main/java/com/memesphere/domain/notification/converter/NotificationConverter.java
Labels: 🎀 Fix

#108 #107 Fix: 기본 프로필 수정
  src/main/java/com/memesphere/domain/image/controller/ImageController.java
  src/main/java/com/memesphere/domain/image/service/ProfileService.java
  src/main/java/com/memesphere/domain/user/dto/request/SignUpRequest.java
Labels: 🎀 Fix

#110 #104 Fix: 알림 변동성 체크 로직 변경
  src/main/java/com/memesphere/domain/chartdata/repository/ChartDataRepository.java
  src/main/java/com/memesphere/domain/chartdata/scheduler/ChartDataScheduler.java
  src/main/java/com/memesphere/domain/chartdata/service/ChartDataQueryService.java
  src/main/java/com/memesphere/domain/chartdata/service/ChartDataQueryServiceImpl.java
  src/main/java/com/memesphere/domain/memecoin/service/MemeCoinQueryService.java
  src/main/java/com/memesphere/domain/memecoin/service/MemeCoinQueryServiceImpl.java
  src/main/java/com/memesphere/domain/notification/service/PushNotificationService.java
  src/main/java/com/memesphere/domain/notification/service/PushNotificationServiceImpl.java
Labels: 🎀 Fix

#111 #104 Fix: 스케줄러 시간 변경
  src/main/java/com/memesphere/domain/chartdata/scheduler/ChartDataScheduler.java
Labels: 🎀 Fix

#113 #112 Feat: 네이버 검색어 트렌드 API
  src/main/java/com/memesphere/domain/naver/controller/SearchTrendController.java
  src/main/java/com/memesphere/domain/naver/dto/request/SearchRequest.java
  src/main/java/com/memesphere/domain/naver/dto/response/SearchResponse.java
  src/main/java/com/memesphere/domain/naver/service/SearchTrendService.java
  src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
Labels: 📬 API

#114 #104 Fix: loggedInUser 기능 추가
  src/main/java/com/memesphere/domain/chartdata/scheduler/ChartDataScheduler.java
  src/main/java/com/memesphere/domain/chartdata/service/ChartDataQueryService.java
  src/main/java/com/memesphere/domain/chartdata/service/ChartDataQueryServiceImpl.java
  src/main/java/com/memesphere/domain/memecoin/service/MemeCoinQueryService.java
  src/main/java/com/memesphere/domain/memecoin/service/MemeCoinQueryServiceImpl.java
  src/main/java/com/memesphere/domain/notification/controller/PushNotificationController.java
  src/main/java/com/memesphere/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/memesphere/domain/notification/service/PushNotificationServiceImpl.java
  src/main/java/com/memesphere/global/jwt/LoggedInUserStore.java
Labels: 🎀 Fix

#116 #115 Fix: 서치 리스트 응답 형식 수정
  src/main/java/com/memesphere/domain/search/converter/SearchConverter.java
  src/main/java/com/memesphere/domain/search/dto/response/SearchListPreviewResponse.java
Labels: 🎀 Fix

#119 #106 Feat: 비밀번호 찾기
  build.gradle
  src/main/java/com/memesphere/domain/user/controller/UserController.java
  src/main/java/com/memesphere/domain/user/converter/UserConverter.java
  src/main/java/com/memesphere/domain/user/dto/response/EmailResponse.java
  src/main/java/com/memesphere/domain/user/entity/User.java
  src/main/java/com/memesphere/domain/user/service/AuthService.java
  src/main/java/com/memesphere/domain/user/service/AuthServiceImpl.java
  src/main/java/com/memesphere/domain/user/service/GoogleServiceImpl.java
  src/main/java/com/memesphere/domain/user/service/KakaoServiceImpl.java
  src/main/java/com/memesphere/domain/user/service/MailService.java
  src/main/java/com/memesphere/domain/user/service/MailServiceImpl.java
  src/main/java/com/memesphere/domain/user/service/UserService.java
  src/main/java/com/memesphere/domain/user/service/UserServiceImpl.java
  src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#121 #120 Fix: Notification Response에서 코인 아이디 추가
  src/main/java/com/memesphere/domain/notification/converter/NotificationConverter.java
  src/main/java/com/memesphere/domain/notification/dto/response/NotificationResponse.java
Labels: 🎀 Fix

#125 #124 Fix: 채팅 좋아요 여부 확인 기능 추가
  src/main/java/com/memesphere/domain/chat/controller/ChatController.java
  src/main/java/com/memesphere/domain/chat/converter/ChatConverter.java
  src/main/java/com/memesphere/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/memesphere/domain/chat/service/ChatService.java
Labels: 🎀 Fix

#128 #127 Fix: 채팅 좋아요 여부 확인 로직 변경
  src/main/java/com/memesphere/domain/chat/converter/ChatConverter.java
Labels: 🎀 Fix

#130 #129 Fix: 채팅 조회 가능범위 변경
  src/main/java/com/memesphere/domain/chat/controller/ChatController.java
  src/main/java/com/memesphere/domain/chat/converter/ChatConverter.java
Labels: 🎀 Fix

#135 #134 Fix: GRID뷰 페이지당 12개 코인으로 수정
  src/main/java/com/memesphere/domain/collection/service/CollectionQueryServiceImpl.java
  src/main/java/com/memesphere/domain/dashboard/service/DashboardQueryServiceImpl.java
  src/main/java/com/memesphere/domain/search/service/SearchQueryServiceImpl.java
Labels: 🎀 Fix

#136 #132 Deploy: CORS 배포설정
  src/main/java/com/memesphere/global/config/CorsMvcConfig.java
Labels: 🌏 Deploy

#140 #139 Fix: 최신 채팅 500에러 해결
  src/main/java/com/memesphere/domain/chat/controller/ChatController.java
Labels: 🐞 BugFix

#133 #131 Fix: 바이낸스 api 응답 자료형 변경
  src/main/java/com/memesphere/domain/chartdata/converter/ChartDataConverter.java
  src/main/java/com/memesphere/domain/chartdata/entity/ChartData.java
  src/main/java/com/memesphere/domain/collection/converter/CollectionConverter.java
  src/main/java/com/memesphere/domain/collection/dto/response/CollectionGridPreviewResponse.java
  src/main/java/com/memesphere/domain/collection/dto/response/CollectionListPreviewResponse.java
  src/main/java/com/memesphere/domain/dashboard/converter/DashboardConverter.java
  src/main/java/com/memesphere/domain/dashboard/dto/response/DashboardTrendResponse.java
  src/main/java/com/memesphere/domain/detail/converter/DetailConverter.java
  src/main/java/com/memesphere/domain/detail/dto/response/PriceInfoResponse.java
  src/main/java/com/memesphere/domain/notification/service/PushNotificationServiceImpl.java
  src/main/java/com/memesphere/domain/search/converter/SearchConverter.java
  src/main/java/com/memesphere/domain/search/dto/response/SearchGridPreviewResponse.java
  src/main/java/com/memesphere/domain/search/dto/response/SearchListPreviewResponse.java
Labels: 🐞 BugFix, 🎀 Fix

#142 #126 Feat: Thymeleaf를 이용한 이메일 전송
  src/main/java/com/memesphere/domain/user/converter/UserConverter.java
  src/main/java/com/memesphere/domain/user/service/MailServiceImpl.java
  src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/memesphere/global/config/SecurityConfig.java
  src/main/resources/static/css/mail.css
  src/main/resources/templates/mail.html
Labels: ✨ Feature

#144 #143 Fix: 밈코인 랭크 10분마다 업데이트 추가
  src/main/java/com/memesphere/domain/chartdata/scheduler/ChartDataScheduler.java
Labels: 🎀 Fix

#147 #1 Chore: ec2 주소 관련 파일 수정
  src/main/java/com/memesphere/global/config/CorsMvcConfig.java
  src/main/java/com/memesphere/global/config/SwaggerConfig.java
Labels: 🛠️ Chore
